<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class chapter_itemsTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('chapter_items')->insert([
            [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 1,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 2,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 3,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 4,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 5,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 2,
                'chapter_item_num' => 1,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 2,
                'chapter_item_num' => 2,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 2,
                'chapter_item_num' => 3,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 2,
                'chapter_item_num' => 4,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 2,
                'chapter_item_num' => 5,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 3,
                'chapter_item_num' => 1,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 3,
                'chapter_item_num' => 2,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 3,
                'chapter_item_num' => 3,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 3,
                'chapter_item_num' => 4,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 3,
                'chapter_item_num' => 5,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 4,
                'chapter_item_num' => 1,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 4,
                'chapter_item_num' => 2,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 4,
                'chapter_item_num' => 3,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 4,
                'chapter_item_num' => 4,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 4,
                'chapter_item_num' => 5,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 5,
                'chapter_item_num' => 1,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 5,
                'chapter_item_num' => 2,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 5,
                'chapter_item_num' => 3,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 5,
                'chapter_item_num' => 4,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 1,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 5,
                'chapter_item_num' => 5,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 2,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 1,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 2,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 2,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 2,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 3,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 2,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 4,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'language_id' => 2,
                'url' => 'https://www.google.co.jp/',
                'chapter_num' => 1,
                'chapter_item_num' => 5,
                'chapter_item' => 'Helloworld',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
